name: Manual Update Medical News

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run crawler
        env:
          VITE_BOLTDATABASE_URL: ${{ secrets.VITE_BOLTDATABASE_URL }}
          VITE_BOLTDATABASE_ANON_KEY: ${{ secrets.VITE_BOLTDATABASE_ANON_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: node crawl-supabase.cjs
      
      - name: Report completion
        run: echo "✓ Manual news update completed successfully"
