name: update-news

on:
  workflow_dispatch: {}        # ✅ manual "Run workflow" button
  schedule:
    - cron: "0 */8 * * *"      # ✅ automatic, every 8 hours

permissions:
  contents: write
  actions: read
  id-token: write

concurrency:
  group: update-news
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      # Required for DB
      VITE_BOLTDATABASE_URL: ${{ secrets.VITE_BOLTDATABASE_URL }}
      VITE_BOLTDATABASE_ANON_KEY: ${{ secrets.VITE_BOLTDATABASE_ANON_KEY }}
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      # Optional AI / images
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Quick sanity
        shell: bash
        run: |
          set -e
          echo "Node: $(node -v)"
          echo "Root listing:"; ls -la || true
          echo "scripts/: "; ls -la scripts || true
          echo "public/:  "; ls -la public || true

      - name: Install dependencies
        shell: bash
        run: |
          set -e
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Check required secrets
        shell: bash
        run: |
          set -e
          [ -n "$VITE_BOLTDATABASE_URL" ] || { echo "❌ VITE_BOLTDATABASE_URL missing"; exit 1; }
          [ -n "$VITE_BOLTDATABASE_ANON_KEY" ] || { echo "❌ VITE_BOLTDATABASE_ANON_KEY missing"; exit 1; }
          [ -n "$SU]()
